const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const root = path.join(__dirname, '..');
const chat = fs.readFileSync(path.join(root, 'chat.js'), 'utf8');
const chatCss = fs.readFileSync(path.join(root, 'chat.css'), 'utf8');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const ui = fs.readFileSync(path.join(root, 'app-ui.js'), 'utf8');
const core = fs.readFileSync(path.join(root, 'app-core.js'), 'utf8');
const mainCss = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');
const sw = fs.readFileSync(path.join(root, 'service-worker.js'), 'utf8');
const workflow = fs.readFileSync(path.join(root, '.github', 'workflows', 'deploy-pages.yml'), 'utf8');
const baseMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260924003000_secure_chat.sql'), 'utf8');
const refineMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260924014500_refine_chat_directory.sql'), 'utf8');
const maturityMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260924111500_chat_maturity.sql'), 'utf8');
const operationalMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260924201500_operational_alerts_chat_retention.sql'), 'utf8');
const chatPolicyFixMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260924211500_fix_chat_reply_policy.sql'), 'utf8');

new vm.Script(chat, { filename: 'chat.js' });

assert.match(html, /id="chat" class="view hidden"/, 'chat must remain an isolated app view');
assert.match(html, /data-v="chat"[^>]*>[\s\S]*?<span>Chat<\/span>[\s\S]*?id="chatUnreadBadge"/, 'bottom navigation must expose Chat with an unread badge');
assert.match(html, /class="chatTeamConsole"[\s\S]*Anaesthetic Team/, 'Anaesthetic Team must be displayed as the main chat transcript');
assert.match(html, /id="chatTeamMessages"/, 'team chat must expose a scrolling multi-message transcript');
assert.match(html, /id="chatTeamComposer"[\s\S]*id="chatTeamInput"/, 'group messages must be sent directly from the Chat home screen');
assert.match(html, /id="chatConversationList"[^>]*aria-label="Private conversations"/, 'private conversations must remain visually separate from the team transcript');
assert.match(html, /One-to-one messages with nurses in the current roster/, 'private messaging must explicitly follow roster membership');
assert.match(html, /Staff coordination only\.<\/b> Do not share patient-identifiable or clinical information in chat\./, 'chat must retain the patient-information safety notice');
assert.match(html, /id="chatTeamInput"[^>]*maxlength="2000"/, 'group chat must remain bounded plain text');
assert.match(html, /id="chatMessageInput"[^>]*maxlength="2000"/, 'private chat must remain bounded plain text');
assert.doesNotMatch(html.slice(html.indexOf('<section id="chat"'), html.indexOf('<section id="admin"')), /type="file"|accept="image|camera|microphone|video|location/i, 'chat must not expose attachment or media controls');
assert.match(html, /chat\.css\?v=37\.40/, 'chat styling must be versioned with the app');
assert.match(html, /chat\.js\?v=37\.40/, 'chat client must be versioned with the app');
assert.match(ui, /function onboardingChatPage\(\)/, 'onboarding must include a dedicated Team chat page');
assert.match(ui, /if\(onboardingChatIntro\)return\[onboardingChatPage\(\)\]/, 'existing users must receive a one-page chat introduction rather than replaying the full guide');
assert.match(ui, /anaes_chat_intro_v37_31/, 'the chat introduction must be shown once per device');
assert.match(ui, /What’s new · Chat/, 'existing users must see the refreshed Chat introduction as an intentional one-time onboarding moment');
assert.match(ui, /onboardingChatPage\(\),[\s\S]*Your identity/, 'new users must see chat as part of the normal onboarding sequence');
assert.match(ui, /Coordinate without leaving the roster\./, 'chat onboarding must explain the feature in plain language');
assert.match(ui, /Chat never changes the roster by itself/, 'chat onboarding must explain that chat never replaces roster updates');
assert.match(ui, /Mentions[\s\S]*@mentions and replies[\s\S]*Privacy[\s\S]*14 days/, 'chat onboarding must introduce mentions, replies, privacy-safe notifications and retention');
assert.match(core, /var viewScrollPositions=\{today:0,changes:0,breaks:0,chat:0,roster:0,admin:0\}/, 'each primary view must keep its own scroll position');
const showSource = core.slice(core.indexOf('function show(v)'), core.indexOf('function previewExtension', core.indexOf('function show(v)')));
assert.match(showSource, /viewScrollPositions\[previous\]=Math\.max\(0,Number\(window\.scrollY\|\|0\)\)/, 'tab switching must remember the outgoing tab position');
assert.match(showSource, /window\.scrollTo\(0,restoreY\)/, 'tab switching must restore the destination tab without smooth scrolling');
assert.doesNotMatch(showSource, /window\.scrollTo\(0,0\)|classList\.add\('viewEntering'\)/, 'tab switching must not force the page to the top or animate the entire view');
assert.match(mainCss, /body\.tabSwitching \.screenHeader[\s\S]*transition:none!important/, 'scroll-edge header transitions must be frozen during a tab switch');

assert.match(chatCss, /\.chatTeamConsole\{[\s\S]*minmax\(250px,330px\)/, 'team transcript must provide a substantial scrolling message area');
assert.match(chatCss, /\.chatTeamLine\{[\s\S]*grid-template-columns:auto auto minmax\(0,1fr\)/, 'team messages must render as compact continuous chat lines rather than bubbles');
assert.match(chatCss, /\.chatSafetyNotice\{[\s\S]*padding:8px 10px/, 'the safety notice must remain compact');
assert.match(chatCss, /\.chatMemberChoice:disabled\{[\s\S]*opacity:1/, 'unregistered roster members must stay legible rather than looking broken');
assert.match(chatCss, /body\.dark/, 'chat must include dark-mode styling');

assert.match(chat, /var PRIVATE_PAGE_SIZE=40;/, 'private chat must page messages instead of loading full history');
assert.match(chat, /var TEAM_PAGE_SIZE=30;/, 'team chat must load a bounded recent transcript');
assert.match(chat, /window\.openChatView=chatOpenView/, 'installed Chat shortcuts must be able to open the Team chat home safely');
assert.match(chat, /\.limit\(TEAM_PAGE_SIZE\)/, 'team message history must be paginated');
assert.match(chat, /\.lt\('id',chatState\.teamOldestMessageId\)/, 'older team messages must use keyset pagination');
assert.match(chat, /\.limit\(PRIVATE_PAGE_SIZE\)/, 'private message history must be paginated');
assert.match(chat, /\.lt\('id',chatState\.oldestMessageId\)/, 'older private messages must use keyset pagination');
assert.match(chat, /channel\('anaesthetic-chat-v4-'/, 'chat must use a realtime channel separate from roster sync');
assert.doesNotMatch(chat, /changesChannel|loadSharedData|scheduleSharedReload|night_changes|night_overtime|rotation_versions|roster_nights/, 'chat client must not call roster synchronization or roster tables');
assert.match(chat, /typeof TEAM!=='undefined'&&Array\.isArray\(TEAM\)/, 'private-message availability must be derived from the current roster team');
assert.match(chat, /chatRosterKeys\(\)\.filter/, 'private-message picker must be generated from roster membership');
assert.match(chat, /Has not registered in Night Roster yet/, 'roster members without an app account must be shown with a clear availability state');
assert.match(chat, /chatDisplayName\(/, 'chat should use roster display names without exposing emails');
assert.match(chat, /chatSamePerson/, 'alternate sign-in identities for one person must be treated as the same chat sender');
assert.doesNotMatch(chat, /select\([^\n]*email|\.email\b/, 'chat client must not request or render email addresses');
assert.match(chat, /var row=\{conversation_id:conversationId,body:body\}/, 'message send must not supply sender identity from the browser');
assert.doesNotMatch(chat, /row\.sender_id|row\.sender_display_name/, 'reply support must not allow the browser to choose sender identity');
assert.match(chat, /body\.textContent=chatMessageBodyText\(message\)/, 'message text must be rendered as text rather than HTML');
assert.doesNotMatch(chat, /accept swap|approve swap|request swap|swap request/i, 'chat must not implement a formal swap workflow');
assert.match(html, /id="chatTeamNewMessages"/, 'team chat must expose a jump-to-new-messages control');
assert.match(html, /id="chatPrivateNewMessages"/, 'private chat must expose a jump-to-new-messages control');
assert.match(html, /id="chatMessageActionSheet"[\s\S]*Copy message[\s\S]*Delete message/, 'message actions must retain copy and limited deletion');
assert.match(chat, /chatMessageReplyBtn[\s\S]*Reply/, 'message actions must add a focused Reply action without adding reactions or editing');
assert.match(chat, /function chatDateLabel\(/, 'chat must render date separators');
assert.match(chat, /function chatUnreadDivider\(/, 'chat must render a new-messages divider');
assert.match(chat, /function chatNearBottom\(/, 'chat must detect whether the reader is already at the bottom');
assert.match(chat, /chatState\.teamNewBelow\+=1|chatState\.privateNewBelow\+=1/, 'incoming messages must not drag a reader away from older history');
assert.match(chat, /chatRetryFailed/, 'failed sends must remain retryable');
assert.match(chat, /chatCompleteSend\(result,'team'\)\.catch\(function\(\)\{\}\)/, 'a successfully inserted Team message must not become a failed Retry item because post-send housekeeping fails');
assert.match(chat, /try\{await chatMarkRead[\s\S]*catch\(error\)\{\}[\s\S]*dispatchChatPush[\s\S]*catch\(error\)\{\}/, 'read-state and notification work must be isolated from the saved-message result');
assert.match(chat, /DELETE_WINDOW_MS=10\*60\*1000/, 'sender deletion must be limited to a short window');
assert.match(chat, /navigator\.clipboard\.writeText/, 'message copy must use the clipboard API');
assert.match(chat, /client\.rpc\('chat_overview_v2'\)/, 'opening chat must use one compact overview RPC');
const startSessionSource = chat.slice(chat.indexOf('async function chatStartSession()'), chat.indexOf('function chatScheduleSessionStart', chat.indexOf('async function chatStartSession()')));
assert.doesNotMatch(startSessionSource, /chatFetchOverview|chatLoadTeamMessages/, 'chat history must not load during roster startup');
assert.match(chat, /table:'chat_members'/, 'chat must refresh private availability when registered members change');
assert.match(chat, /table:'chat_directory'/, 'chat must refresh private availability when the safe directory changes');
assert.match(chat, /chatSetConnection\('reconnecting'\)|chatSetConnection\('offline'\)|chatSetConnection\('live'\)/, 'chat must expose live, reconnecting and offline states');
assert.match(chatCss, /\.chatDateSeparator/, 'date separators must be styled');
assert.match(chatCss, /\.chatUnreadDivider/, 'unread divider must be styled');
assert.match(chatCss, /\.chatRetryBtn/, 'failed-message Retry must be styled');

assert.match(baseMigration, /create table if not exists public\.chat_messages/, 'base chat schema must remain intact');
assert.match(refineMigration, /create table if not exists public\.chat_directory/, 'refined directory must be stored separately from private profiles');
assert.match(refineMigration, /create table if not exists chat_private\.identity_links/, 'alternate login identities must be linked in the private chat schema');
assert.match(refineMigration, /grant select on table public\.chat_directory to authenticated/, 'authenticated members may read only the safe directory');
assert.match(refineMigration, /Active members can view roster chat directory/, 'directory access must be RLS protected');
assert.match(refineMigration, /person_key=participant\.person_key/, 'private conversation RLS must compare canonical chat identity');
assert.match(refineMigration, /new\.sender_id:=auth\.uid\(\)/, 'database trigger must still stamp the authenticated sender id');
assert.match(refineMigration, /new\.sender_display_name:=v_name/, 'sender display identity must be stamped server-side');
assert.match(refineMigration, /security invoker/, 'unread aggregation must continue to respect RLS');
assert.doesNotMatch(refineMigration, /alter table public\.user_profiles|create policy[\s\S]*on public\.user_profiles/i, 'private user profile visibility must remain unchanged');
assert.doesNotMatch(refineMigration, /insert into public\.night_|update public\.night_|delete from public\.night_|insert into public\.roster_|update public\.roster_|delete from public\.roster_/i, 'chat refinement must not mutate roster data');
assert.match(maturityMigration, /add column if not exists deleted_at timestamptz/, 'chat maturity migration must support sender deletion markers');
assert.match(maturityMigration, /Senders can delete recent own messages[\s\S]*interval '10 minutes'/, 'message deletion must be constrained by RLS and time');
assert.match(maturityMigration, /create or replace function public\.chat_overview_v2\(\)[\s\S]*security invoker/, 'chat overview must preserve caller RLS');
assert.match(maturityMigration, /supabase_realtime add table public\.chat_directory/, 'directory changes must be published for realtime availability');
assert.match(chat, /CHAT_MESSAGE_FIELDS='[^']*reply_to_message_id/, 'message reads must include reply metadata');
assert.match(chat, /function chatReplyPreviewNode\(/, 'replies must render a compact quoted source preview');
assert.match(chat, /reply_to_message_id=Number\(replyId\)/, 'reply sends must persist the selected source message');
assert.match(chat, /function chatRenderMentionMenu\(/, 'Team chat must provide roster-based mention autocomplete');
assert.match(chat, /chatRosterDirectory\(\).*filter/s, 'mention suggestions must derive from the current roster chat directory');
assert.match(chat, /'@'\+entry\.person_key/, 'mentions must insert the server-recognised roster identity token');
assert.match(chat, /Messages are automatically removed after 14 days\./, 'chat must tell users about the retention period');
assert.match(chatCss, /\.chatComposerReply/, 'reply composer preview must be styled');
assert.match(chatCss, /\.chatMentionMenu/, 'mention autocomplete must be styled');
assert.match(operationalMigration, /add column if not exists reply_to_message_id bigint[\s\S]*references public\.chat_messages\(id\)/, 'reply targets must be stored as message references');
assert.match(chatPolicyFixMigration, /chat_private\.reply_belongs_to_conversation\([\s\S]*reply_to_message_id[\s\S]*conversation_id/, 'reply targets must be constrained to the same conversation without recursively querying the message policy');
assert.doesNotMatch(chatPolicyFixMigration, /from public\.chat_messages replied/, 'the active reply policy must not recurse through chat_messages RLS');
assert.match(operationalMigration, /now\(\) - interval '14 days'/, 'chat retention must delete only messages older than 14 days');
assert.match(operationalMigration, /cron\.schedule\([\s\S]*chat-retention-14-days[\s\S]*prune_expired_chat_messages/, '14-day retention must run automatically server-side');

assert.doesNotMatch(maturityMigration, /insert into public\.night_|update public\.night_|delete from public\.night_|insert into public\.roster_|update public\.roster_|delete from public\.roster_/i, 'chat maturity changes must remain isolated from roster data');

const appShell = sw.slice(sw.indexOf('const APP_SHELL = ['), sw.indexOf('];', sw.indexOf('const APP_SHELL = [')) + 2);
assert.doesNotMatch(appShell, /chat\.js|chat\.css/, 'chat assets must not be mandatory for service-worker installation');
assert.match(workflow, /- name: Build public app files\n        run: npm run build/, 'deployment must build the chat and push assets');
const viteConfig = fs.readFileSync(path.join(root, 'vite.config.mts'), 'utf8');
for (const asset of ['chat.css', 'chat.js', 'push.js']) assert.ok(viteConfig.includes(`'${asset}'`), `${asset} must be included in the Pages artifact`);

console.log('Group transcript, roster-based private list, privacy and pagination checks passed.');
