const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const root = path.join(__dirname, '..');
const chat = fs.readFileSync(path.join(root, 'chat.js'), 'utf8');
const push = fs.readFileSync(path.join(root, 'push.js'), 'utf8');
const chatCss = fs.readFileSync(path.join(root, 'chat.css'), 'utf8');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const ui = fs.readFileSync(path.join(root, 'app-ui.js'), 'utf8');
const core = fs.readFileSync(path.join(root, 'app-core.js'), 'utf8');
const mainCss = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');
const presentationCss = fs.readFileSync(path.join(root, 'src', 'presentation.css'), 'utf8');
const sw = fs.readFileSync(path.join(root, 'service-worker.js'), 'utf8');
const workflow = fs.readFileSync(path.join(root, '.github', 'workflows', 'deploy-pages.yml'), 'utf8');
const release = JSON.parse(fs.readFileSync(path.join(root, 'release.json'), 'utf8'));
const releaseVersionPattern = release.version.replace(/\./g, '\\.');
const baseMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260924003000_secure_chat.sql'), 'utf8');
const refineMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260924014500_refine_chat_directory.sql'), 'utf8');
const maturityMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260924111500_chat_maturity.sql'), 'utf8');
const operationalMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260924201500_operational_alerts_chat_retention.sql'), 'utf8');
const chatPolicyFixMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20260924211500_fix_chat_reply_policy.sql'), 'utf8');
const logicFoundationMigration = fs.readFileSync(path.join(root, 'supabase', 'migrations', '20261002120000_logic_foundation_v47.sql'), 'utf8');

new vm.Script(chat, { filename: 'chat.js' });

assert.match(html, /id="chat" class="view hidden"/, 'chat must remain an isolated app view');
assert.match(html, /data-v="chat"[^>]*>[\s\S]*?<span>Chat<\/span>[\s\S]*?id="chatUnreadBadge"/, 'bottom navigation must expose Chat with an unread badge');
assert.match(html, /id="chatTeamEntry"[\s\S]*Anaesthetic Team/, 'Anaesthetic Team must be pinned as the first inbox conversation');
assert.match(html, /id="chatInboxHeading">Team chat<[\s\S]*Everyone on tonight’s roster/, 'the group conversation must be labelled plainly as Team chat');
assert.match(html, /id="chatTeamEntry"[\s\S]*Chat with everyone on tonight’s roster/, 'the team row must explain who receives a Team chat message');
assert.match(html, /id="chatNewPrivateBtn"[\s\S]*New private chat/, 'the private-message action must use a visible text label, not an icon alone');
assert.match(html, /data-switch-state-for="pushTeamToggle">On/, 'Team chat notifications must expose a non-colour On state label');
assert.match(html, /data-switch-state-for="pushPrivateToggle">On/, 'Private-message notifications must expose a non-colour On state label');
assert.match(push, /function pushSetSwitchState\(/, 'dynamic notification preferences must share the explicit switch-state renderer');
assert.match(push, /teamMuted\?\(mutedUntil\?'Muted':'Off'\):'On'/, 'Team chat mute state must be described as On, Off or Muted');
assert.match(html, /id="chatTeamThread"[\s\S]*id="chatTeamMessages"/, 'team chat must open into a dedicated scrolling thread');
assert.match(html, /id="chatTeamThread"[\s\S]*id="chatTeamComposer"[\s\S]*id="chatTeamInput"/, 'group messages must be sent from the dedicated team thread');
assert.match(html, /id="chatConversationList"[^>]*aria-label="Private conversations"/, 'private conversations must remain a distinct inbox section');
assert.match(html, /Private messages[\s\S]*One-to-one chats/, 'private messaging must remain explicitly one-to-one');
assert.match(html, /Staff coordination only[\s\S]*No patient information[\s\S]*Messages removed after 14 days/, 'chat must retain the patient-information safety notice');
assert.match(html, /id="chatTeamInput"[^>]*maxlength="2000"/, 'group chat must remain bounded plain text');
assert.match(html, /id="chatMessageInput"[^>]*maxlength="2000"/, 'private chat must remain bounded plain text');
assert.doesNotMatch(html.slice(html.indexOf('<section id="chat"'), html.indexOf('<section id="admin"')), /type="file"|accept="image|camera|microphone|video|location/i, 'chat must not expose attachment or media controls');
assert.match(html, new RegExp(`chat\\.css\\?v=${releaseVersionPattern}`), 'chat styling must be versioned with the app');
assert.match(html, new RegExp(`chat\\.js\\?v=${releaseVersionPattern}`), 'chat client must be versioned with the app');
assert.match(ui, /function featureEducationPage\(key\)[\s\S]*if\(key==='chat'\)[\s\S]*Team chat, when you need it\./, 'Chat must retain a dedicated contextual education page');
assert.match(ui, /roster:viewchange[\s\S]*showFeatureEducation\(view,false\)/, 'Chat education must be triggered contextually when the user opens the view');
assert.match(ui, /anaes_chat_intro_v37_31/, 'the contextual Chat education must preserve the earlier one-time device marker for compatibility');
assert.match(ui, /markEducationSeen\(key,1\)/, 'completed feature education must be recorded once per device');
assert.doesNotMatch(ui.slice(ui.indexOf('function onboardingPages'), ui.indexOf('function bindGuideActions')), /featureEducationPage\('chat'\)|onboardingChatPage\(\)/, 'new users must not receive a separate Chat training page during first-use onboarding');
assert.match(ui, /Anaesthetic Team reaches everyone on tonight’s roster/, 'Chat education must explain the team audience in plain language');
assert.match(ui, /Chat never changes the roster\.[\s\S]*Changes/, 'Chat education must explain that agreed roster changes are recorded separately');
assert.match(ui, /never patient-identifiable or clinical information/, 'Chat education must keep the patient-information safety boundary explicit');
assert.match(core, /var viewScrollPositions=\{today:0,changes:0,breaks:0,chat:0,roster:0,admin:0\}/, 'each primary view must keep its own scroll position');
const showSource = core.slice(core.indexOf('function show(v)'), core.indexOf('function previewExtension', core.indexOf('function show(v)')));
assert.match(showSource, /viewScrollPositions\[previous\]=Math\.max\(0,Number\(window\.scrollY\|\|0\)\)/, 'tab switching must remember the outgoing tab position');
assert.match(showSource, /window\.scrollTo\(0,restoreY\)/, 'tab switching must restore the destination tab without smooth scrolling');
assert.doesNotMatch(showSource, /window\.scrollTo\(0,0\)|classList\.add\('viewEntering'\)/, 'tab switching must not force the page to the top or animate the entire view');
assert.match(mainCss, /body\.tabSwitching \.screenHeader[\s\S]*transition:none!important/, 'scroll-edge header transitions must be frozen during a tab switch');

assert.match(chatCss, /\.chatTeamConsole\{[\s\S]*minmax\(250px,330px\)/, 'team transcript must provide a substantial scrolling message area');
assert.match(chatCss, /\.chatTeamLine\{[\s\S]*grid-template-columns:auto auto minmax\(0,1fr\)/, 'team messages must render as compact continuous chat lines rather than bubbles');
assert.match(chatCss, /\.chatSafetyNotice\{[\s\S]*padding:8px 10px/, 'the safety notice must remain compact');
assert.match(chatCss, /\.chatMemberChoice:disabled\{[\s\S]*opacity:1/, 'unregistered roster members must stay legible rather than looking broken');
assert.match(chatCss, /body\.dark/, 'chat must include dark-mode styling');
assert.match(presentationCss, /40\.1 Chat polish/, 'the current Chat polish layer must stay identifiable and reviewable');
assert.match(presentationCss, /#chat \.chatHeaderCompose span\{display:inline!important/, 'New private chat must keep a visible text label on phone and desktop');
assert.match(presentationCss, /#chat \.chatMessageText\{color:inherit!important;font-size:var\(--chat-readable\)!important/, 'message text must keep the readable night-shift type scale');
assert.match(presentationCss, /#chat \.chatPrivateMessage\.own \.chatPrivateBubble\{[\s\S]*background:var\(--premium-blue\)!important/, 'private outgoing messages must remain visually distinct without changing delivery behaviour');
assert.match(presentationCss, /#chat \.chatComposerGlass\{[\s\S]*border:1px solid[\s\S]*border-radius:26px/, 'the composer must remain a single polished surface rather than nested bordered controls');

assert.match(chat, /var PRIVATE_PAGE_SIZE=40;/, 'private chat must page messages instead of loading full history');
assert.match(chat, /var TEAM_PAGE_SIZE=30;/, 'team chat must load a bounded recent transcript');
assert.match(chat, /window\.openChatView=chatOpenView/, 'installed Chat shortcuts must be able to open the Team chat home safely');
assert.match(chat, /\.limit\(TEAM_PAGE_SIZE\)/, 'team message history must be paginated');
assert.match(chat, /\.lt\('id',chatState\.teamOldestMessageId\)/, 'older team messages must use keyset pagination');
assert.match(chat, /\.limit\(PRIVATE_PAGE_SIZE\)/, 'private message history must be paginated');
assert.match(chat, /\.lt\('id',chatState\.oldestMessageId\)/, 'older private messages must use keyset pagination');
assert.match(chat, /channel\('anaesthetic-chat-v4-'/, 'chat must use a realtime channel separate from roster sync');
assert.doesNotMatch(chat, /changesChannel|loadSharedData|scheduleSharedReload|night_changes|night_overtime|rotation_versions|roster_nights/, 'chat client must not call roster synchronization or roster tables');
assert.match(chat, /typeof TEAM!=='undefined'&&Array\.isArray\(TEAM\)/, 'private-message availability must be derived from the current roster team');
assert.match(chat, /chatRosterKeys\(\)\.filter/, 'private-message picker must be generated from roster membership');
assert.match(chat, /Has not registered in Night Roster yet/, 'roster members without an app account must be shown with a clear availability state');
assert.match(chat, /chatDisplayName\(/, 'chat should use roster display names without exposing emails');
assert.match(chat, /chatSamePerson/, 'alternate sign-in identities for one person must be treated as the same chat sender');
assert.doesNotMatch(chat, /select\([^\n]*email|\.email\b/, 'chat client must not request or render email addresses');
assert.match(chat, /var row=\{conversation_id:conversationId,body:body\}/, 'message send must not supply sender identity from the browser');
assert.doesNotMatch(chat, /row\.sender_id|row\.sender_display_name/, 'reply support must not allow the browser to choose sender identity');
assert.match(chat, /body\.textContent=chatMessageBodyText\(message\)/, 'message text must be rendered as text rather than HTML');
assert.doesNotMatch(chat, /accept swap|approve swap|request swap|swap request/i, 'chat must not implement a formal swap workflow');
assert.match(html, /id="chatTeamNewMessages"/, 'team chat must expose a jump-to-new-messages control');
assert.match(html, /id="chatPrivateNewMessages"/, 'private chat must expose a jump-to-new-messages control');
assert.match(html, /id="chatMessageActionSheet"[\s\S]*Copy message[\s\S]*Delete message/, 'message actions must retain copy and limited deletion');
assert.match(chat, /chatMessageReplyBtn[\s\S]*Reply/, 'message actions must add a focused Reply action without adding reactions or editing');
assert.match(chat, /function chatDateLabel\(/, 'chat must render date separators');
assert.match(chat, /function chatUnreadDivider\(/, 'chat must render a new-messages divider');
assert.match(chat, /function chatNearBottom\(/, 'chat must detect whether the reader is already at the bottom');
assert.match(chat, /chatState\.teamNewBelow\+=1|chatState\.privateNewBelow\+=1/, 'incoming messages must not drag a reader away from older history');
assert.match(chat, /chatRetryFailed/, 'failed sends must remain retryable');
assert.match(chat, /chatCompleteSend\(result,'team'\)\.catch\(function\(\)\{\}\)/, 'a successfully inserted Team message must not become a failed Retry item because post-send housekeeping fails');
assert.match(chat, /try\{await chatMarkRead[\s\S]*catch\(error\)\{\}[\s\S]*dispatchChatPush[\s\S]*catch\(error\)\{\}/, 'read-state and notification work must be isolated from the saved-message result');
assert.match(chat, /DELETE_WINDOW_MS=10\*60\*1000/, 'sender deletion must be limited to a short window');
assert.match(chat, /navigator\.clipboard\.writeText/, 'message copy must use the clipboard API');
assert.match(chat, /client\.rpc\('chat_overview_v2'\)/, 'opening chat must use one compact overview RPC');
const startSessionSource = chat.slice(chat.indexOf('async function chatStartSession()'), chat.indexOf('function chatScheduleSessionStart', chat.indexOf('async function chatStartSession()')));
assert.doesNotMatch(startSessionSource, /chatFetchOverview|chatLoadTeamMessages/, 'chat history must not load during roster startup');
assert.match(chat, /table:'chat_members'/, 'chat must refresh private availability when registered members change');
assert.match(chat, /table:'chat_directory'/, 'chat must refresh private availability when the safe directory changes');
assert.match(chat, /chatSetConnection\('reconnecting'\)|chatSetConnection\('offline'\)|chatSetConnection\('live'\)/, 'chat must expose live, reconnecting and offline states');
assert.match(chatCss, /\.chatDateSeparator/, 'date separators must be styled');
assert.match(chatCss, /\.chatUnreadDivider/, 'unread divider must be styled');
assert.match(chatCss, /\.chatRetryBtn/, 'failed-message Retry must be styled');

assert.match(baseMigration, /create table if not exists public\.chat_messages/, 'base chat schema must remain intact');
assert.match(refineMigration, /create table if not exists public\.chat_directory/, 'refined directory must be stored separately from private profiles');
assert.match(refineMigration, /create table if not exists chat_private\.identity_links/, 'alternate login identities must be linked in the private chat schema');
assert.match(refineMigration, /grant select on table public\.chat_directory to authenticated/, 'authenticated members may read only the safe directory');
assert.match(refineMigration, /Active members can view roster chat directory/, 'directory access must be RLS protected');
assert.match(refineMigration, /person_key=participant\.person_key/, 'private conversation RLS must compare canonical chat identity');
assert.match(refineMigration, /new\.sender_id:=auth\.uid\(\)/, 'database trigger must still stamp the authenticated sender id');
assert.match(refineMigration, /new\.sender_display_name:=v_name/, 'sender display identity must be stamped server-side');
assert.match(refineMigration, /security invoker/, 'unread aggregation must continue to respect RLS');
assert.doesNotMatch(refineMigration, /alter table public\.user_profiles|create policy[\s\S]*on public\.user_profiles/i, 'private user profile visibility must remain unchanged');
assert.doesNotMatch(refineMigration, /insert into public\.night_|update public\.night_|delete from public\.night_|insert into public\.roster_|update public\.roster_|delete from public\.roster_/i, 'chat refinement must not mutate roster data');
assert.match(maturityMigration, /add column if not exists deleted_at timestamptz/, 'chat maturity migration must support sender deletion markers');
assert.match(maturityMigration, /Senders can delete recent own messages[\s\S]*interval '10 minutes'/, 'message deletion must be constrained by RLS and time');
assert.match(maturityMigration, /create or replace function public\.chat_overview_v2\(\)[\s\S]*security invoker/, 'chat overview must preserve caller RLS');
assert.match(maturityMigration, /supabase_realtime add table public\.chat_directory/, 'directory changes must be published for realtime availability');
assert.match(chat, /CHAT_MESSAGE_FIELDS='[^']*reply_to_message_id[^']*client_message_id/, 'message reads must include reply and idempotency metadata');
assert.match(chat, /chat_send_message_v47/, 'new chat sends must use the idempotent schema-47 send function when available');
assert.match(chat, /chatRetryFailed\(message,kind\)[\s\S]*message\.client_message_id/, 'Retry must reuse the original client message id');
assert.match(chat, /chat_mark_read_v47/, 'read state must use the monotonic schema-47 function when available');
assert.match(logicFoundationMigration, /chat_messages_sender_client_message_uq[\s\S]*sender_id,client_message_id/, 'chat send idempotency must be enforced server-side');
assert.match(logicFoundationMigration, /chat_mark_read_v47[\s\S]*greatest\(/, 'read state must never move backwards across devices');
assert.match(chat, /function chatReplyPreviewNode\(/, 'replies must render a compact quoted source preview');
assert.match(chat, /reply_to_message_id=Number\(replyId\)/, 'reply sends must persist the selected source message');
assert.match(chat, /function chatRenderMentionMenu\(/, 'Team chat must provide roster-based mention autocomplete');
assert.match(chat, /chatRosterDirectory\(\).*filter/s, 'mention suggestions must derive from the current roster chat directory');
assert.match(chat, /'@'\+entry\.person_key/, 'mentions must insert the server-recognised roster identity token');
assert.match(chat, /automatically removed after 14 days/i, 'chat safety information must retain the 14-day retention period');
assert.match(chatCss, /\.chatComposerReply/, 'reply composer preview must be styled');
assert.match(chatCss, /\.chatMentionMenu/, 'mention autocomplete must be styled');
assert.match(operationalMigration, /add column if not exists reply_to_message_id bigint[\s\S]*references public\.chat_messages\(id\)/, 'reply targets must be stored as message references');
assert.match(chatPolicyFixMigration, /chat_private\.reply_belongs_to_conversation\([\s\S]*reply_to_message_id[\s\S]*conversation_id/, 'reply targets must be constrained to the same conversation without recursively querying the message policy');
assert.doesNotMatch(chatPolicyFixMigration, /from public\.chat_messages replied/, 'the active reply policy must not recurse through chat_messages RLS');
assert.match(operationalMigration, /now\(\) - interval '14 days'/, 'chat retention must delete only messages older than 14 days');
assert.match(operationalMigration, /cron\.schedule\([\s\S]*chat-retention-14-days[\s\S]*prune_expired_chat_messages/, '14-day retention must run automatically server-side');

assert.doesNotMatch(maturityMigration, /insert into public\.night_|update public\.night_|delete from public\.night_|insert into public\.roster_|update public\.roster_|delete from public\.roster_/i, 'chat maturity changes must remain isolated from roster data');

const appShell = sw.slice(sw.indexOf('const APP_SHELL = ['), sw.indexOf('];', sw.indexOf('const APP_SHELL = [')) + 2);
assert.doesNotMatch(appShell, /chat\.js|chat\.css/, 'chat assets must not be mandatory for service-worker installation');
assert.match(workflow, /test:[\s\S]*- name: Build public app files\n        run: npm run build[\s\S]*actions\/upload-artifact@v4/, 'verified chat and push assets must be built once and preserved for deployment');
const viteConfig = fs.readFileSync(path.join(root, 'vite.config.mts'), 'utf8');
for (const asset of ['chat.css', 'chat.js', 'push.js']) assert.ok(viteConfig.includes(`'${asset}'`), `${asset} must be included in the Pages artifact`);

console.log('Group transcript, roster-based private list, privacy and pagination checks passed.');
