const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const index=read('index.html'),client=read('night-welcome.js'),css=read('night-welcome.css'),vite=read('vite.config.mts'),worker=read('service-worker.js');
assert.match(index,/id="nightWelcomeHero"/,'Night must expose the personalised welcome hero');
assert.match(index,/night-welcome\.js\?v=/,'Night welcome runtime must be versioned');
assert.match(index,/night-welcome\.css\?v=/,'Night welcome styles must be versioned');
assert.match(client,/currentPrivateProfile/,'Welcome must prefer the private personal profile');
assert.match(client,/currentUserProfile/,'Welcome must fall back to the approved profile');
assert.match(client,/professionalName/,'Welcome must support the professional roster identity');
assert.match(client,/plausiblePersonalName/,'Welcome must validate a saved personal name before using it');
assert.match(client,/GENERIC_NAME_LEADS/,'Welcome must reject obvious sentence-like values from the personal name field');
assert.match(client,/words\.length>3/,'Welcome must reject long phrase-like values instead of treating them as names');
assert.match(client,/if\(personalName\)return personalName/,'A valid in-app personal name must have first priority');
assert.match(client,/if\(rosterFirstName\)return rosterFirstName/,'The imported roster identity must be the automatic fallback');
assert.match(client,/if\(accountFirstName\)return accountFirstName/,'The approved account display name must be the final named fallback');
const privateProfileIndex=client.indexOf('currentPrivateProfile'),rosterIndex=client.indexOf("typeof myName==='function'"),approvedProfileIndex=client.indexOf('currentUserProfile');
assert.ok(privateProfileIndex>=0&&rosterIndex>privateProfileIndex&&approvedProfileIndex>rosterIndex,'Greeting identity priority must be in-app name, imported roster name, then approved account name');
assert.match(client,/greeting_enabled/,'Welcome must respect the saved greeting preference');
assert.match(client,/prefers-reduced-motion/,'Welcome must respect reduced motion');
assert.match(client,/sessionStorage\.getItem\(TYPED_KEY\)/,'Typing should happen once per session');
assert.match(client,/anaes_night_welcome_typed_v3/,'The hardened welcome should receive a fresh one-time session reveal after update');
assert.match(client,/NAME_PAUSE_MS=420/,'The welcome must pause deliberately before revealing the nurse name');
assert.match(client,/NAME_CHAR_MS=92/,'The nurse name must type more slowly than the greeting');
assert.match(client,/GREETING_CHAR_MS=50/,'The greeting itself must remain calmly readable');
assert.match(client,/typingDelay\(index,parts\)/,'Typing cadence must distinguish greeting and nurse name');
assert.doesNotMatch(client,/Andre|André|Michael/,'Welcome must never hard-code an individual nurse name');
assert.match(css,/nightWelcomeTitle/,'Welcome must have a dedicated visual hierarchy');
assert.match(css,/@media\(max-width:520px\)\{#today #nightWelcomeSubtitle\{display:none\}\}/,'Phone layouts must remove the redundant orientation subtitle');
assert.doesNotMatch(index,/nightWelcomeEyebrow/, 'welcome must not repeat a redundant Your night heading');
assert.match(vite,/night-welcome\.js/,'Build must ship the welcome runtime');
assert.match(vite,/night-welcome\.css/,'Build must ship the welcome styles');
assert.match(worker,/night-welcome\.js\?v=/,'Installed PWA must cache the welcome runtime');
assert.match(worker,/night-welcome\.css\?v=/,'Installed PWA must cache the welcome styles');
console.log('Personal Night welcome contracts passed.');
