const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const index=read('index.html'),client=read('night-welcome.js'),css=read('night-welcome.css'),vite=read('vite.config.mts'),worker=read('service-worker.js');
assert.match(index,/id="nightWelcomeHero"/,'Night must expose the personalised welcome hero');
assert.match(index,/night-welcome\.js\?v=/,'Night welcome runtime must be versioned');
assert.match(index,/night-welcome\.css\?v=/,'Night welcome styles must be versioned');
assert.match(client,/currentPrivateProfile/,'Welcome must prefer the private personal profile');
assert.match(client,/currentUserProfile/,'Welcome must fall back to the approved profile');
assert.match(client,/professionalName/,'Welcome must support the professional roster identity');
assert.match(client,/greeting_enabled/,'Welcome must respect the saved greeting preference');
assert.match(client,/prefers-reduced-motion/,'Welcome must respect reduced motion');
assert.match(client,/sessionStorage\.getItem\(TYPED_KEY\)/,'Typing should happen once per session');
assert.doesNotMatch(client,/Andre|André/,'Welcome must never hard-code an individual nurse name');
assert.match(css,/nightWelcomeTitle/,'Welcome must have a dedicated visual hierarchy');
assert.match(vite,/night-welcome\.js/,'Build must ship the welcome runtime');
assert.match(vite,/night-welcome\.css/,'Build must ship the welcome styles');
assert.match(worker,/night-welcome\.js\?v=/,'Installed PWA must cache the welcome runtime');
assert.match(worker,/night-welcome\.css\?v=/,'Installed PWA must cache the welcome styles');
console.log('Personal Night welcome contracts passed.');
