const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const unified = read('src/product-unified.css');
const tailwind = read('src/tailwind.css');
const designSystem = read('docs/DESIGN_SYSTEM.md');
function includesAll(source, values, label) { for (const value of values) assert.ok(source.includes(value), `${label} is missing ${value}`); }
includesAll(tailwind, ['@import "./presentation.css";','@import "./account-admin-polish.css";','@import "./rudder-navigation.css";','@import "./product-polish.css";','@import "./product-unified.css";'], 'Production presentation cascade');
assert.ok(!tailwind.includes('@import "./product-coherence.css";'), 'historical coherence layer must not remain active');
assert.ok(!tailwind.includes('@import "./product-coherence-bridge.css";'), 'historical migration bridge must not remain active');
assert.ok(!tailwind.includes('@import "./product-coherence-correction.css";'), '47.0 corrective layer must stay retired');
assert.ok(tailwind.indexOf('@import "./product-unified.css";') > tailwind.indexOf('@import "./product-polish.css";'), 'product-unified.css must remain the final product authority');
includesAll(unified, ['--unified-content-width:','--unified-space-1:','--unified-radius-lg:','--unified-fast:','--unified-ease:','#today .nightUnifiedHero','#changes .changesDatePanel','#breaks .breaksContextPanel','#chat .chatRosterContext','.nightTeamIdentityContext','input[type="date"]::-webkit-datetime-edit','#changes .workflowSteps','#today #personalNightCard > .personalHeroSurface','#breaks .personalBreakSummary','#chat .chatInboxTeamRow','.quickActionsExperience','.bottom.reactTabs','#accountSheet','.personalisationGroup','.headerLiveChip',':focus-visible','@media (max-width: 430px)','@media (prefers-reduced-transparency: reduce)','@media (prefers-reduced-motion: reduce)','@media (prefers-contrast: more)'], 'Unified product contract');
assert.ok(!unified.includes('.hidden {'), 'product system must not redefine runtime visibility state');
assert.ok(!unified.includes('--liquid-critical:'), 'product system must not redefine clinical critical colour');
assert.ok(!unified.includes('--liquid-warning:'), 'product system must not redefine clinical warning colour');
assert.ok(!unified.includes('--liquid-success:'), 'product system must not redefine clinical success colour');
assert.ok((unified.match(/!important/g) || []).length <= 760, 'single final product authority override budget must remain bounded');
includesAll(designSystem, ['role tonight, their break, changes requiring attention, the team plan','`product-unified.css` is the single final product-wide presentation authority','Night → Changes → Actions → Breaks → Chat → Account','Do not create another final override stylesheet'], 'Design-system ownership');
console.log('unified product coherence contract tests passed');
