const assert = require('node:assert/strict');
const fs = require('node:fs');
const read = f => fs.readFileSync(f,'utf8');
const html=read('index.html'),workflow=read('src/changes-workflow.tsx'),account=read('src/legacy-ui/account.js'),context=read('src/selected-night.ts');
assert.match(html,/id="changesWorkflowExperience">\s*<div class="changesWorkflowTabs"[\s\S]*id="changesWorkflowState"[^>]*><\/div>\s*<\/div>/,'working fallback must occupy the same host React replaces');
assert.doesNotMatch(workflow,/fallback\?\.classList|legacyState\?\.classList/,'no separate duplicate fallback to hide');
assert.equal((html.match(/class="changesWorkflowTabs"/g)||[]).length,1);
assert.match(context,/composeSelectedNight/,'one selected-night layout composer');
assert.match(context,/panel.replaceChildren\(context\)/,'remove obsolete context wrappers');
assert.match(account,/outlet.replaceChildren\(target\)/,'one actual Account destination at a time');
assert.match(account,/accountPresentationPages/,'retain page DOM and unsaved state on Back');
assert.match(account,/key!=='home'/,'Done belongs only on Account home');
assert.match(account,/refreshPushSettings/,'Notifications refreshes the existing controls when opened');
assert.doesNotMatch(read('src/clinical-experience.tsx'),/Your break · \{model.formattedDate\}/,'date belongs in selected-night context');
assert.match(read('src/clinical-experience.tsx'),/className="timelineEnd"/,'timeline endpoint has its own layout anchor');
const sync=read('src/legacy-ui/sync.js');
assert.match(sync,/waitingWorkerIsRedundant\(\)/,'same-version waiting workers remain safely dismissed');
console.log('Single workflow host, Account outlet, selected-night context and timeline endpoint contracts passed');
