const assert = require('node:assert/strict');
const fs = require('node:fs');
const read = file => fs.readFileSync(file, 'utf8');
const css = read('src/product-unified.css');
const imports = read('src/tailwind.css');
const nav = read('src/rudder-navigation.css');
assert.equal((imports.match(/@import "\.\/product-.*\.css"/g)||[]).length,1,'one active product system');
assert.equal((css.match(/!important/g)||[]).length,0,'canonical product rules must not use priority patches');
assert.equal((nav.match(/!important/g)||[]).length,0,'dock must have normal canonical ownership');
for(const file of ['product-polish','product-coherence','product-coherence-bridge','product-coherence-correction']) assert.equal(fs.existsSync(`src/${file}.css`),false,'superseded CSS must be removed');
for(const file of ['src/presentation.css','src/account-admin-polish.css','styles.css','chat.css']) assert.equal((read(file).match(/!important/g)||[]).length,0,`${file} must not override current presentation`);
assert.match(imports,/\.hidden, \[hidden\] \{ display: none !important; \}/,'visibility is one explicit semantic invariant');
for(const value of ['--unified-space-1: 4px','--unified-space-2: 8px','--unified-space-3: 12px','--unified-space-4: 16px','--unified-space-5: 24px','--unified-space-6: 32px']) assert.ok(css.includes(value));
assert.match(css,/prefers-reduced-motion/); assert.match(nav,/safe-bottom/);
assert.doesNotMatch(css,/,\s*@keyframes/,'screen transition selectors must not swallow a keyframe rule');
assert.doesNotMatch(css,/--liquid-(?:critical|success|warning):/,'presentation must not redefine clinical colours');
assert.match(nav,/repeat\(5,minmax\(0,1fr\)\)/,'equal-width persistent dock');
assert.match(nav,/\.navTaskBadge/,'badges use the shared icon stage');
console.log('Canonical design system, layer ownership, visibility and dock contracts passed');
