/* Education, onboarding and reusable feature-guide ownership. */
function educationVersions(){
  return{main:4,night:1,changes:3,actions:1,breaks:3,chat:3,roster:1,account:2}
}
function educationVersion(key){return Number(educationVersions()[key]||1)}
function educationState(){
  var state={main:0,night:0,chat:0,changes:0,actions:0,breaks:0,roster:0,account:0};
  try{var saved=JSON.parse(appStorage.getItem('anaes_education_state_v1')||'{}');Object.keys(state).forEach(function(key){if(Number(saved[key])>0)state[key]=Number(saved[key])})}catch(error){}
  if(appStorage.getItem('anaes_onboarding_complete_v34'))state.main=Math.max(state.main,2);
  if(appStorage.getItem('anaes_chat_intro_v37_31'))state.chat=Math.max(state.chat,1);
  return state
}
function educationSeen(key,version){return Number(educationState()[key]||0)>=Number(version||educationVersion(key))}
function markEducationSeen(key,version){
  var state=educationState();state[key]=Math.max(Number(state[key]||0),Number(version||educationVersion(key)));try{appStorage.setItem('anaes_education_state_v1',JSON.stringify(state))}catch(error){}
  if(key==='main')appStorage.setItem('anaes_onboarding_complete_v34','1');if(key==='chat')appStorage.setItem('anaes_chat_intro_v37_31','1');refreshEducationMarkers()
}
function refreshEducationMarkers(){
  ['changes','breaks','chat'].forEach(function(view){var button=document.querySelector('.bottom button[data-v="'+view+'"]');if(!button)return;var fresh=!educationSeen(view,educationVersion(view));button.classList.toggle('educationNew',fresh);if(fresh)button.setAttribute('data-education-label','New');else button.removeAttribute('data-education-label')})
}
function onboardingMiniNight(selected){
  return'<div class="onboardingProductPreview onboardingNightPreview" aria-hidden="true"><div class="onboardingPreviewHead"><span>YOUR NIGHT</span><small>Example</small></div><div class="onboardingPreviewPerson"><span class="onboardingPreviewAvatar">'+esc(selected?professionalName(selected).charAt(0).toUpperCase():'A')+'</span><div><b>'+esc(selected?professionalName(selected):'Your roster name')+'</b><small>Your allocation stays first</small></div></div><div class="onboardingPreviewFacts"><span><small>Duty</small><b>Second Part</b></span><span><small>Break</small><b>First break</b></span><span><small>Colleague</small><b>Team</b></span></div></div>'
}
function onboardingWorkflowPreview(){
  return'<div class="onboardingProductPreview onboardingWorkflowPreview" aria-hidden="true"><div><span>1</span><b>Staffing</b><small>Who changed?</small></div><i></i><div><span>2</span><b>Allocation</b><small>Only if needed</small></div><i></i><div><span>3</span><b>Confirm</b><small>Share once</small></div></div>'
}
function onboardingActionsPreview(){
  return'<div class="onboardingProductPreview onboardingActionsPreview" aria-hidden="true"><div><span>−</span><b>Report absence</b></div><div><span>+</span><b>Add overtime</b></div><div class="wide"><span>✓</span><b>Review this night</b><small>Only turns amber when something needs attention</small></div></div>'
}
function featureEducationLabel(key){
  return key==='clockchange'?'Clock change':key==='night'?'Night':key==='changes'?'Changes':key==='actions'?'Actions':key==='breaks'?'Breaks':key==='chat'?'Chat':key==='roster'?'Full roster':key==='account'?'Account & Personalise':'Guide'
}
function featureEducationPage(key){
  if(key==='clockchange'){var date=onboardingClockChangeDate||cur().date,timing=nightDutyTiming(date),detail=clockChangeDetailFor(date);return'<div class="onboardingProductPreview clockChangeOnboardingPreview" aria-hidden="true"><div class="clockChangePreviewClock"><span>02</span><i>→</i><span>'+(timing.direction==='back'?'02':'03')+'</span></div><div class="clockChangePreviewSplit"><span><small>FIRST PART</small><b>'+esc(timing.firstPeriodDisplay)+'</b><em>'+esc(detail.partHoursLabel)+' actual</em></span><i></i><span><small>SECOND PART</small><b>'+esc(timing.secondPeriod)+'</b><em>'+esc(detail.partHoursLabel)+' actual</em></span></div></div><span class="onboardingEyebrow">Clock change night</span><h2 id="onboardingTitle">The app keeps both parts equal.</h2><p>'+esc(detail.transitionLabel)+'. Night Roster automatically moves the handover to <b>'+esc(detail.handoverDisplay)+'</b> so First Part and Second Part each work <b>'+esc(detail.partHoursLabel)+'</b> of real elapsed duty.</p><div class="onboardingCallout"><b>No manual adjustment needed</b><span>The roster names and break ownership stay the same. Only the duty handover time changes for this night.</span></div><p class="onboardingFootnote">Night, Breaks, live duty status and roster summaries all use this same equal-duty timing.</p>'}
  if(key==='night')return onboardingMiniNight(myName())+'<span class="onboardingEyebrow">Night</span><h2 id="onboardingTitle">Your own night is the first answer.</h2><p>The dark Your night card shows your duty, break, colleague and live 00:00–07:00 rail. Team allocation is the one place for the shared plan, with Full roster inside it when you need every night.</p><div class="onboardingFeatureList"><div><b>Selected night</b><span>The date at the top controls Night, Changes and Breaks</span></div><div><b>Decision card</b><span>Amber appears only when a real allocation needs attention</span></div><div><b>Changes tonight</b><span>Recent staffing and allocation activity stays compact below the plan</span></div></div><p class="onboardingFootnote">Clock-change nights explain themselves on the live rail and keep First Part and Second Part equal in real elapsed time.</p>';
  if(key==='actions')return onboardingActionsPreview()+'<span class="onboardingEyebrow">Actions</span><h2 id="onboardingTitle">The centre + is your shortcut.</h2><p>Actions opens a focused sheet for the selected night, so common jobs do not require hunting through screens.</p><div class="onboardingFeatureList"><div><b>Staffing</b><span>Report an absence or add overtime cover</span></div><div><b>Review</b><span>Jump straight to an allocation or confirmation that needs attention</span></div><div><b>Communication</b><span>Start a private message or share Night Roster by QR or another app</span></div></div>';
  if(key==='account')return'<div class="onboardingProductPreview onboardingAccountPreview" aria-hidden="true"><span class="onboardingPreviewAvatar">AB</span><div><small>PERSONALISATION STUDIO</small><b>Me · Our Shift</b><span>Your styling stays personal. Shift identity is shared.</span></div></div><span class="onboardingEyebrow">Account & Personalise</span><h2 id="onboardingTitle">Your avatar is the home for settings.</h2><p>Tap the avatar at the top to open Account, then choose a page. Back returns to Account; Done closes Account home. Personalisation Studio separates <b>Me</b> from <b>Our Shift</b>, so you can customise your own experience without confusing it with the shared team identity.</p><div class="onboardingFeatureList"><div><b>Me</b><span>Photo or avatar, accent, text size, motion and greeting</span></div><div><b>Our Shift</b><span>Name, tagline, symbol and picture shown to the team</span></div><div><b>Account</b><span>Separate pages for appearance, notifications, security and App & Help</span></div></div><p class="onboardingFootnote">Shared shift identity is team-only. Never upload patient photographs or patient information.</p>';
  if(key==='roster')return'<div class="onboardingProductPreview onboardingRosterPreview" aria-hidden="true"><div><small>FIRST PART</small><b>2 nurses</b></div><div><small>SECOND PART</small><b>2 nurses</b></div><div><small>PAGER / RELIEVER</small><b>Labour Ward order</b></div></div><span class="onboardingEyebrow">Full roster</span><h2 id="onboardingTitle">Use Full roster when you need the wider picture.</h2><p>On Night, open <b>Team allocation</b> first for the selected night. Full roster sits inside that section as the deeper view across published nights, with role grouping and search.</p><div class="onboardingCallout onboardingCalmCallout"><b>One route, no duplicate buttons</b><span>Your personal card stays focused on your own duty while Team allocation owns the shared-plan detail.</span></div>';
  if(key==='chat')return'<div class="onboardingProductPreview featureChatPreview" aria-hidden="true"><span>'+interfaceIcon('chat')+'</span><div><i></i><i></i><i></i></div></div><span class="onboardingEyebrow">Team Chat</span><h2 id="onboardingTitle">Team chat, when you need it.</h2><p>The shared shift identity names the team conversation. Team chat reaches everyone on tonight’s roster, while private conversations are for one registered colleague.</p><div class="onboardingFeatureList"><div><b>Team</b><span>Coordinate with tonight’s whole roster</span></div><div><b>Private</b><span>Message one registered team member</span></div><div><b>Alerts</b><span>Notifications are optional and can be changed in Account</span></div><div><b>Safety</b><span>Roster coordination only, never patient-identifiable or clinical information</span></div></div><p class="onboardingFootnote">Chat never changes the roster. Record an agreed staffing or role change separately in Changes.</p>';
  if(key==='changes')return onboardingWorkflowPreview()+'<span class="onboardingEyebrow">Changes</span><h2 id="onboardingTitle">Only exceptions need your attention.</h2><p>The standard calculated night stays automatic. Use Changes for a confirmed absence, overtime cover or an agreed night-only allocation, then follow Staffing → Allocation → Confirm.</p><div class="onboardingFeatureList"><div><b>Amber means act</b><span>A specific decision card appears when someone must choose an allocation</span></div><div><b>Review changes</b><span>The blue review action appears only when the plan is genuinely ready to confirm</span></div><div><b>Activity</b><span>Activity for this night keeps the history secondary and expandable</span></div></div>';
  return'<div class="onboardingProductPreview onboardingBreakPreview" aria-hidden="true"><div><small>FIRST BREAK</small><b>Your name</b><span>03:30 onward</span></div><div><small>SECOND BREAK</small><b>Team</b><span>00:00 to 03:30</span></div><button type="button" tabindex="-1">Jump to me</button></div><span class="onboardingEyebrow">Breaks</span><h2 id="onboardingTitle">Your break is already highlighted.</h2><p>Breaks follows the same selected night and live staffing plan as Night. Use Jump to me when you want your own row immediately.</p><div class="onboardingCallout onboardingCalmCallout"><b>One shared plan</b><span>Staffing and role changes flow through to Breaks automatically, including equal-duty clock-change timing.</span></div>'
}
function appGuidePage(){
  return'<span class="onboardingEyebrow">Tutorial & app guide</span><h2 id="onboardingTitle">Learn the whole app or jump to one feature.</h2><p>The complete tutorial and these short lessons are built from the same current feature guide.</p><div class="appGuideList appGuideListExpanded"><button type="button" class="appGuidePrimary" data-guide-action="tutorial"><span class="appGuideIcon">▶</span><span><b>Replay complete tutorial</b><small>All current and recently added features, step by step</small></span><i>›</i></button><button type="button" data-guide-feature="night"><span class="appGuideIcon">'+interfaceIcon('night')+'</span><span><b>Night</b><small>Your assignment, timeline, Team allocation and activity</small></span><i>›</i></button><button type="button" data-guide-feature="changes"><span class="appGuideIcon">'+interfaceIcon('staffing')+'</span><span><b>Changes</b><small>Staffing → Allocation → Confirm and decision cards</small></span><i>›</i></button><button type="button" data-guide-feature="actions"><span class="appGuideIcon">+</span><span><b>Actions</b><small>Absence, overtime, review, messaging and sharing shortcuts</small></span><i>›</i></button><button type="button" data-guide-feature="breaks"><span class="appGuideIcon">'+interfaceIcon('task')+'</span><span><b>Breaks</b><small>Your break and the shared schedule</small></span><i>›</i></button><button type="button" data-guide-feature="chat"><span class="appGuideIcon">'+interfaceIcon('chat')+'</span><span><b>Team Chat</b><small>Shared shift chat, private messages and optional alerts</small></span><i>›</i></button><button type="button" data-guide-feature="roster"><span class="appGuideIcon">☷</span><span><b>Full roster</b><small>The wider published roster and role groups</small></span><i>›</i></button><button type="button" data-guide-feature="account"><span class="appGuideIcon">Aa</span><span><b>Account & Personalise</b><small>Me, Our Shift, appearance, notifications and passkeys</small></span><i>›</i></button><button type="button" data-guide-action="share"><span class="appGuideIcon">↗</span><span><b>Share & install</b><small>QR code, phone sharing and install help</small></span><i>›</i></button><button type="button" data-guide-action="updates"><span class="appGuideIcon">↺</span><span><b>What’s new & version history</b><small>Latest improvements and every previous release</small></span><i>›</i></button></div>'
}
function onboardingPages(){
  if(onboardingGuideMenu)return[appGuidePage()];if(onboardingFeatureKey||onboardingChatIntro)return[featureEducationPage(onboardingFeatureKey||'chat')];
  var accountName=currentUserProfile&&currentUserProfile.display_name||'',selected=myName()||TEAM.find(function(name){return sameNurse(name,accountName)})||'';
  return[
    '<span class="onboardingEyebrow">Welcome</span><h2 id="onboardingTitle">First, which roster name is yours?</h2><p>Night Roster uses this to bring your own allocation and break to the front on this device.</p><div class="onboardingIdentityPreview"><span>'+(selected?esc(professionalName(selected).charAt(0).toUpperCase()):'?')+'</span><div><b>'+(selected?esc(professionalName(selected)):'Choose your roster name')+'</b><small>'+(selected?'Highlights your own night on this device':'You can change this later in Account')+'</small></div></div><label class="onboardingNameLabel"><span>Roster name</span><select id="onboardingNamePick"><option value="">Choose your name</option>'+TEAM.map(function(name){return'<option value="'+esc(name)+'" '+(sameNurse(name,selected)?'selected':'')+'>'+esc(professionalName(name))+'</option>'}).join('')+'</select></label><p class="onboardingFootnote">This never changes the shared roster or anyone else’s allocation.</p>',
    onboardingMiniNight(selected)+'<span class="onboardingEyebrow">Night</span><h2 id="onboardingTitle">Your night stays first.</h2><p>The dark card gives you duty, break, colleague and the live timeline immediately. The compact shift, nurse count and date context stays linked across Night, Changes and Breaks.</p><div class="onboardingFeatureList"><div><b>Team allocation</b><span>The one route to the selected night’s shared roles, with Full roster inside</span></div><div><b>Changes tonight</b><span>A compact activity timeline shows what changed and who recorded it</span></div><div><b>Clock changes</b><span>The live rail clearly explains repeated or skipped hours and keeps both parts equal</span></div></div>',
    onboardingWorkflowPreview()+'<span class="onboardingEyebrow">Changes</span><h2 id="onboardingTitle">Only exceptions need your attention.</h2><p>The normal calculated roster is automatic. If something genuinely changes, follow Staffing → Allocation → Confirm.</p><div class="onboardingCallout"><b>One decision, one action</b><span>When an allocation is unresolved, Night shows one amber decision card instead of repeated warnings.</span></div>',
    onboardingActionsPreview()+'<span class="onboardingEyebrow">Actions</span><h2 id="onboardingTitle">Use the centre + for common jobs.</h2><p>Actions keeps the selected night in context while giving you fast routes to report an absence, add overtime, review the plan, message a colleague or share the app.</p><div class="onboardingCallout onboardingCalmCallout"><b>Attention stays meaningful</b><span>The indicator is reserved for genuine work that needs review.</span></div>',
    featureEducationPage('breaks'),
    featureEducationPage('chat'),
    featureEducationPage('account'),
    '<div class="onboardingProductPreview onboardingSharePreview" aria-hidden="true"><span>QR</span><div><b>Share Night Roster</b><small>Scan, send or copy the public app link</small></div></div><span class="onboardingEyebrow">Share, install & help</span><h2 id="onboardingTitle">You can always find your way back.</h2><p>Share Night Roster uses a QR code or your phone’s share sheet. Account also keeps installation help, What’s new, version history and this complete tutorial available at any time.</p><div class="onboardingFeatureList"><div><b>Install</b><span>Add the PWA for a full-screen experience and automatic update checks</span></div><div><b>What’s new</b><span>See the improvements worth knowing after an update</span></div><div><b>Tutorial & app guide</b><span>Replay everything or jump straight to one feature</span></div></div><button type="button" class="onboardingShareShortcut" data-share-night-roster><span><b>Share Night Roster</b><small>Show the QR code or use another app</small></span><i>›</i></button>'
  ]
}
function bindGuideActions(){
  Array.prototype.forEach.call(document.querySelectorAll('[data-guide-feature]'),function(button){button.onclick=function(){var key=button.getAttribute('data-guide-feature');onboardingGuideMenu=false;onboardingReplay=true;onboardingFeatureKey=key||'';onboardingChatIntro=key==='chat';onboardingStep=0;onboardingDirection=1;renderOnboarding()}});
  Array.prototype.forEach.call(document.querySelectorAll('[data-guide-view]'),function(button){button.onclick=function(){var view=button.getAttribute('data-guide-view'),dialog=byId('onboardingDialog');onboardingGuideMenu=false;onboardingReplay=false;if(dialog&&dialog.open)dialog.close();show(view);if(view!=='today')setTimeout(function(){showFeatureEducation(view,true)},160)}});
  Array.prototype.forEach.call(document.querySelectorAll('[data-guide-action]'),function(button){button.onclick=function(){var action=button.getAttribute('data-guide-action'),dialog=byId('onboardingDialog');if(action==='tutorial'){onboardingGuideMenu=false;onboardingReplay=true;onboardingFeatureKey='';onboardingChatIntro=false;onboardingStep=0;onboardingDirection=1;renderOnboarding();return}onboardingGuideMenu=false;onboardingReplay=false;if(dialog&&dialog.open)dialog.close();if(action==='account')showAccountSheet();else if(action==='share')showShareApp();else if(action==='updates'){renderReleaseNotes(true);var release=byId('releaseNotes');if(release&&!release.open)release.showModal()}}})
}
function renderOnboarding(){
  var dialog=byId('onboardingDialog'),content=byId('onboardingContent'),pages=onboardingPages();if(!dialog||!content)return;
  onboardingStep=Math.max(0,Math.min(pages.length-1,onboardingStep));var feature=onboardingFeatureKey||onboardingChatIntro?'feature':onboardingGuideMenu?'guide':'main';dialog.dataset.onboardingPage=feature==='main'?String(onboardingStep):feature;dialog.classList.toggle('onboardingFeatureIntro',feature==='feature');dialog.classList.toggle('onboardingGuideMode',feature==='guide');
  content.innerHTML=pages[onboardingStep];content.classList.remove('onboardingContentIn','onboardingContentBack');void content.offsetWidth;content.classList.add(onboardingDirection<0?'onboardingContentBack':'onboardingContentIn');
  byId('onboardingProgress').innerHTML=pages.map(function(_,index){return'<span class="'+(index===onboardingStep?'active':'')+'" aria-hidden="true"></span>'}).join('');byId('onboardingProgress').setAttribute('aria-valuenow',String(onboardingStep+1));byId('onboardingProgress').setAttribute('aria-valuemax',String(pages.length));
  byId('onboardingStepLabel').textContent=feature==='guide'?'Tutorial & app guide':feature==='feature'?'Quick tip · '+featureEducationLabel(onboardingFeatureKey||'chat'):(onboardingStep+1)+' of '+pages.length;
  byId('onboardingBackBtn').classList.toggle('hidden',feature!=='main'||onboardingStep===0);byId('onboardingNextBtn').textContent=feature==='guide'?'Done':feature==='feature'?'Got it':onboardingStep===pages.length-1?'Open my night':'Continue';byId('onboardingSkipBtn').textContent=feature==='main'?'Skip for now':'Close';byId('onboardingSkipBtn').classList.toggle('hidden',feature!=='main'||onboardingStep===pages.length-1);
  var select=byId('onboardingNamePick');if(select)select.onchange=function(){if(select.value)appStorage.setItem('anaes_my_name',select.value);else appStorage.removeItem('anaes_my_name');renderOnboarding()};var shareShortcut=document.querySelector('[data-share-night-roster]');if(shareShortcut)shareShortcut.onclick=function(){var dialog=byId('onboardingDialog');if(dialog&&dialog.open)dialog.close();showShareApp()};bindGuideActions();
  if(dialog.open){content.scrollTop=0;var heading=byId('onboardingTitle');if(heading){heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true})}}
}
async function finishOnboarding(){
  var dialog=byId('onboardingDialog');
  if(onboardingGuideMenu){onboardingGuideMenu=false;onboardingReplay=false;if(dialog&&dialog.open)dialog.close();toast('App guide closed');return}
  if(onboardingFeatureKey||onboardingChatIntro){var key=onboardingFeatureKey||'chat';if(key==='clockchange')markClockChangeEducationSeen(onboardingClockChangeDate);else markEducationSeen(key,educationVersion(key));onboardingFeatureKey='';onboardingClockChangeDate='';onboardingChatIntro=false;onboardingReplay=false;if(dialog&&dialog.open)dialog.close();toast(key==='clockchange'?'Clock-change timing understood':featureEducationLabel(key)+' guide completed');return}
  var wasReplay=onboardingReplay,select=byId('onboardingNamePick');if(select&&select.value)appStorage.setItem('anaes_my_name',select.value);onboardingDeferredSession=false;markEducationSeen('main',educationVersion('main'));['night','changes','actions','breaks','chat','roster','account'].forEach(function(key){markEducationSeen(key,educationVersion(key))});onboardingCandidate=false;onboardingReplay=false;onboardingProfileDraft=null;if(dialog&&dialog.open)dialog.close();render();toast(wasReplay?'Tutorial completed':'Your night is ready')
}
function skipOnboardingForNow(){
  var dialog=byId('onboardingDialog');onboardingDeferredSession=true;onboardingReplay=false;onboardingProfileDraft=null;if(dialog&&dialog.open)dialog.close();toast('Tutorial available in Account')
}
function showOnboardingIfNeeded(){
  if(!currentUserProfile||releaseNotesQueued||onboardingDeferredSession||educationSeen('main',educationVersion('main')))return;var dialog=byId('onboardingDialog');if(!dialog||!dialog.showModal)return;onboardingFeatureKey='';onboardingClockChangeDate='';onboardingChatIntro=false;onboardingGuideMenu=false;onboardingReplay=false;onboardingDirection=1;onboardingStep=0;renderOnboarding();setTimeout(function(){if(!dialog.open)dialog.showModal()},cinematicMotionAllowed()?520:40)
}
function showFeatureEducation(key,force){
  if(['changes','breaks','chat'].indexOf(key)<0||!currentUserProfile||!educationSeen('main',2))return;if(!force&&educationSeen(key,educationVersion(key)))return;
  var dialog=byId('onboardingDialog'),release=byId('releaseNotes');if(!dialog||!dialog.showModal||dialog.open||release&&release.open)return;onboardingFeatureKey=key;onboardingChatIntro=key==='chat';onboardingGuideMenu=false;onboardingReplay=false;onboardingDirection=1;onboardingStep=0;renderOnboarding();setTimeout(function(){if(!dialog.open)dialog.showModal()},cinematicMotionAllowed()?240:20)
}
function showClockChangeEducation(date,force){
  var timing=nightDutyTiming(date);if(!timing.isClockChange||!currentUserProfile||!educationSeen('main',2))return;if(!force&&clockChangeEducationSeen(date))return;
  var dialog=byId('onboardingDialog'),release=byId('releaseNotes');if(!dialog||!dialog.showModal||dialog.open||release&&release.open)return;onboardingFeatureKey='clockchange';onboardingClockChangeDate=date;onboardingChatIntro=false;onboardingGuideMenu=false;onboardingReplay=false;onboardingDirection=1;onboardingStep=0;renderOnboarding();setTimeout(function(){if(!dialog.open)dialog.showModal()},cinematicMotionAllowed()?240:20)
}
function bindFeatureEducation(){
  refreshEducationMarkers();
  window.addEventListener('roster:viewchange',function(event){var view=event&&event.detail&&event.detail.view;if(['changes','breaks','chat'].indexOf(view)>=0){refreshEducationMarkers();setTimeout(function(){showFeatureEducation(view,false)},220)}});
  window.addEventListener('roster:release-action',function(event){var detail=event&&event.detail||{},dialog=byId('releaseNotes');if(detail.action==='history'){renderReleaseNotes(true);return}if(dialog&&dialog.open){markCurrentReleaseSeen();dialog.close()}if(detail.action==='guide'){openOnboardingReplay();return}if(detail.action==='share'){showShareApp();return}if(detail.action==='view'&&detail.value){show(detail.value);if(['changes','breaks','chat'].indexOf(detail.value)>=0)setTimeout(function(){showFeatureEducation(detail.value,true)},180)}})
}
function bindOnboarding(){
  var dialog=byId('onboardingDialog'),next=byId('onboardingNextBtn'),back=byId('onboardingBackBtn'),skip=byId('onboardingSkipBtn');if(!next||!back||!skip)return;
  next.onclick=async function(){rememberOnboardingProfile();var last=onboardingPages().length-1;if(onboardingStep<last){onboardingDirection=1;onboardingStep++;renderOnboarding()}else{next.disabled=true;next.textContent=onboardingFeatureKey||onboardingChatIntro||onboardingGuideMenu?'Closing…':'Saving…';await finishOnboarding();next.disabled=false}};back.onclick=function(){if(onboardingStep>0){onboardingDirection=-1;onboardingStep--;renderOnboarding()}};skip.onclick=function(){if(onboardingGuideMenu||onboardingFeatureKey||onboardingChatIntro)finishOnboarding();else skipOnboardingForNow()};
  if(dialog&&typeof dialog.addEventListener==='function')dialog.addEventListener('cancel',function(event){if(onboardingFeatureKey||onboardingChatIntro){event.preventDefault();finishOnboarding();return}onboardingGuideMenu=false;onboardingReplay=false})
}
